source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Kinetic_Example' do
	pod 'Kinetic', :path => '../'
	pod 'WatchdogInspector'

	target 'Kinetic_Tests' do
		pod 'Kinetic', :path => '../'
	end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ENABLE_BITCODE'] = 'NO'
			config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
			config.build_settings['SWIFT_VERSION'] = '3.0'
		end
	end
end