source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'Kinetic_Example' do
  pod 'Kinetic', :path => '../'
  pod 'WatchdogInspector'
end

target 'Kinetic_Tests' do
  pod 'Kinetic', :path => '../'
  pod 'Nimble', '~> 6.0'
end
